In [1]:
import numpy as np
import pandas as pd
import torch 
import matplotlib.pyplot as plt
import seaborn as sns
import math as m
import sympy as sp

In [2]:
x = torch.tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [3]:
x.requires_grad = True

In [4]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], requires_grad=True)

In [5]:
func = 10*(x**2).sum()

In [6]:
func.backward()

In [7]:
func

tensor(6500., grad_fn=<MulBackward0>)

In [8]:
x.grad

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]])

In [9]:
20*x[0,0]

tensor(20., grad_fn=<MulBackward0>)

In [10]:
x.data -= 0.001*x.grad

In [11]:
x.data

tensor([[ 0.9800,  1.9600,  2.9400,  3.9200],
        [ 4.9000,  5.8800,  6.8600,  7.8400],
        [ 8.8200,  9.8000, 10.7800, 11.7600]])

In [12]:
x.grad.zero_

<function Tensor.zero_>